### ISSUE TITLE
Integrate Insulter

### ISSUE THREAD

**Issue by yashmehrotra** [osdc/osdc-bot#2]
Example Usage:

`@osdc-bot insult <name>`

This returns an insult joke with name as it's subject.

**Comment by ryzokuken** [comment]
could i do this? only if you're not already working on this. 
this was what i had in mind http://quandyfactory.com/insult/json

**Comment by 526avijitgupta** [comment]
@ryzokuken I guess Shivan is working on this. Can you confirm this on Gitter with him ?
