### ISSUE TITLE
Improve message parsing

### ISSUE THREAD

**Issue by yashmehrotra** [osdc/osdc-bot#3]
The current parsing flow is very rigid. It should allow for more free statements like:
- @osdc-bot joke
- @osdc-bot tell me a joke
- @osdc-bot joke suna
- @osdc-bot can i hear a joke

Parsing should be done such that all the above should yield a joke.

**Comment by 526avijitgupta** [comment]
To add to the original issue's statement, it's important to take care of false positives like:
- @osdc-bot do not tell me a joke.
- @osdc-bot I'm not willing to hear a joke.

/cc @wimpykid26
