### ISSUE TITLE
Create separate room for testing purposes

### ISSUE THREAD

**Issue by 526avijitgupta** [osdc/osdc-bot#8]
The reasons for having a separate Gitter room for testing:
1. Manual testing - this room can be used to test out local changes freely without having to worry about the main chat being cluttered.
2. Automated testing (A minor possibility, needs further investigation) - The current tests that are being implemented in #5 are just unit tests. It would a great addition if we could add integration tests for the bot, for which this room can be used as a playground!

**Comment by yashmehrotra** [comment]
Done. https://gitter.im/osdc/Bot-Testing
